### ISSUE TITLE
import failed on CUDA devices (CUDA Version: 11.3, torch Version: 1.14.0.dev20221019+cu116)

### ISSUE THREAD

**Issue by liligwu** [pytorch/FBGEMM#1401]
- On a V100 machine (commit 79c8f8ae17e0f2355b0521a2c86ed6cbe63f0cbd)

/# python -c "import fbgemm_gpu"
/dockerx/FBGEMM/fbgemm_gpu/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN2at4_ops7resize_4callERKNS_6TensorEN3c108ArrayRefIlEENS5_8optionalINS5_12MemoryFormatEEE
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/torch/_ops.py", line 501, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator fbgemm::jagged_2d_to_dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/dockerx/FBGEMM/fbgemm_gpu/fbgemm_gpu/__init__.py", line 22, in <module>
    from . import _fbgemm_gpu_docs
  File "/dockerx/FBGEMM/fbgemm_gpu/fbgemm_gpu/_fbgemm_gpu_docs.py", line 18, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/root/miniconda3/lib/python3.9/site-packages/torch/_ops.py", line 505, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

- And on A100:

/# python -c "import fbgemm_gpu"
/workspace/FBGEMM_local/fbgemm_gpu/fbgemm_gpu/fbgemm_gpu_py.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workspace/FBGEMM_local/fbgemm_gpu/fbgemm_gpu/__init__.py", line 22, in <module>
    from . import _fbgemm_gpu_docs
  File "/workspace/FBGEMM_local/fbgemm_gpu/fbgemm_gpu/_fbgemm_gpu_docs.py", line 7, in <module>
    import fbgemm_gpu.split_table_batched_embeddings_ops
  File "/workspace/FBGEMM_local/fbgemm_gpu/fbgemm_gpu/split_table_batched_embeddings_ops.py", line 17, in <module>
    import fbgemm_gpu.split_embedding_codegen_lookup_invokers as invokers
ModuleNotFoundError: No module named 'fbgemm_gpu.split_embedding_codegen_lookup_invokers'

**Comment by super-dainiu** [comment]
Can try downgrading `fbgemm-gpu` by `pip install fbgemm-gpu==0.2.0`

**Comment by liligwu** [comment]
@super-dainiu. I need to build fbgemm_gpu from the source. Do you have any other suggestions? Thank you.

**Comment by liligwu** [comment]
@super-dainiu any solution for this issue, please?

**Comment by super-dainiu** [comment]
I have no suggestions

**Comment by liligwu** [comment]
I mistakenly imported fbgemm_gpu under FBGEMM/fbgemm_gpu directory. Sorry for the false alarm.

**Comment by allenfengjr** [comment]
@liligwu Hello, I also meet this trouble, could you share your solution? I try to append `fbgemm_gpu` under `FBGEMM` and the directory under `python/site-packages`, but I did not solve this.

**Comment by liligwu** [comment]
> @liligwu Hello, I also meet this trouble, could you share your solution? I try to append `fbgemm_gpu` under `FBGEMM` and the directory under `python/site-packages`, but I did not solve this.

Please see the message above yours. https://github.com/pytorch/FBGEMM/issues/1401#issuecomment-1306045821
