### ISSUE TITLE
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'merge_pooled_embeddings'

### ISSUE THREAD

**Issue by bharaniabhishek123** [pytorch/FBGEMM#3481]
I am getting error as below : 

python -c "import torch; import fbgemm_gpu; print(torch.ops.fbgemm.merge_pooled_embeddings)"
WARNING:root:Could not the library 'fbgemm_gpu_py.so': /usr/local/lib/python3.10/dist-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv.  This may be expected depending on the FBGEMM_GPU variant.
WARNING:root:Could not the library 'experimental/gen_ai/fbgemm_gpu_experimental_gen_ai_py.so': /usr/local/lib/python3.10/dist-packages/fbgemm_gpu/experimental/gen_ai/fbgemm_gpu_experimental_gen_ai_py.so: undefined symbol: _ZN4c10d23ncclGetErrorWithVersionE12ncclResult_t.  This may be expected depending on the FBGEMM_GPU variant.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1225, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'merge_pooled_embeddings'

I followed below threads , 
https://github.com/pytorch/FBGEMM/issues/1618
https://github.com/pytorch/FBGEMM/issues/2130

but no luck.

The docker file contains image : nvcr.io/nvidia/pytorch:24.10-py3

**Comment by q10** [comment]
Hi @bharaniabhishek123 , would you happen to know what is the variant (e.g. cpu-only, cuda, rocm) and version of pytorch you are using?  The missing symbols might indicate you are using a different version from what is expected.   The [instructions](https://pytorch.org/FBGEMM/fbgemm_gpu-development/InstallationInstructions.html) we provide cover installing everything from scratch in a fresh Conda environment, including pytorch.

**Comment by bharaniabhishek123** [comment]
Sure, It was fbgemm-gpu (I also tried cuda nightly variant) , Pytorch Version  is 2.5.0a0+e000cf0ad9.nv24.10 .
